In [7]:
#IMQAV - Ingest, Model, Query, Analyze, Visualize

#create array using numpy
import numpy as np
myfirstarray = np.arange(11)
print (myfirstarray)

[ 0  1  2  3  4  5  6  7  8  9 10]


# _Creating a link_    
- [neo4j](http://localhost:7474/browser/)

**Markdown table generator**

[Markdown table generator](https://www.tablesgenerator.com/markdown_tables)

| Sno. | Data |   |   |   |
|------|------|---|---|---|
| 1    | 23   |   |   |   |
| 2    | 34   |   |   |   |
| 3    | 45   |   |   |   |
| 4    | 65   |   |   |   |

__Writing equations__  (raw NB_convert and run in markdown mode)

\begin{align}
\dot{x} & = \sigma(y-x) \\
\dot{x} & = \rho.x + beta.y \\
\sum_{k=1}^n a_k b_k 
\end{align}

In [13]:
#pandas series
import pandas as pd
firstseries = pd.Series([1,2,3,4,np.nan])   #inside the paranthesis we write a list
print(firstseries)

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
dtype: float64


In [20]:
#creating a matrix of 4 rows with 3 values each
numpy_data = np.arange(24).reshape(6,4)
numpy_data2 = np.array(np.arange(12)).reshape(4,3)
print(numpy_data)
print(numpy_data2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [23]:
#creating an index
dates_index = pd.date_range('20180101', periods = 6)
dates_index

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-06'],
              dtype='datetime64[ns]', freq='D')

In [28]:
#creating a data frame
df = pd.DataFrame(numpy_data,index=dates_index,columns=list('ABCD'))
df

A   B   C   D
2018-01-01   0   1   2   3
2018-01-02   4   5   6   7
2018-01-03   8   9  10  11
2018-01-04  12  13  14  15
2018-01-05  16  17  18  19
2018-01-06  20  21  22  23

In [45]:
#creating a dataframe from dictionary
#the columns are arranged alphabetically

df_dict = pd.DataFrame({
    'float': 1.,
    'time' : pd.Timestamp('20180124'),
    'array': np.array([2] * 5),
    'category' : pd.Categorical(['train','test','train','train','train'])
    })

print(df_dict)
df_dict.dtypes     #for datatypes

   array category  float       time
0      2    train    1.0 2018-01-24
1      2     test    1.0 2018-01-24
2      2    train    1.0 2018-01-24
3      2    train    1.0 2018-01-24
4      2    train    1.0 2018-01-24


array                int32
category          category
float              float64
time        datetime64[ns]
dtype: object

In [47]:
print(df.head(3))

            A  B   C   D
2018-01-01  0  1   2   3
2018-01-02  4  5   6   7
2018-01-03  8  9  10  11


In [48]:
df.values      #gives the underlying numpy array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [50]:
df.index

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-06'],
              dtype='datetime64[ns]', freq='D')

In [51]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [52]:
df.describe()

A          B          C          D
count   6.000000   6.000000   6.000000   6.000000
mean   10.000000  11.000000  12.000000  13.000000
std     7.483315   7.483315   7.483315   7.483315
min     0.000000   1.000000   2.000000   3.000000
25%     5.000000   6.000000   7.000000   8.000000
50%    10.000000  11.000000  12.000000  13.000000
75%    15.000000  16.000000  17.000000  18.000000
max    20.000000  21.000000  22.000000  23.000000

In [54]:
#transpose of a dataframe
df.T

2018-01-01  2018-01-02  2018-01-03  2018-01-04  2018-01-05  2018-01-06
A           0           4           8          12          16          20
B           1           5           9          13          17          21
C           2           6          10          14          18          22
D           3           7          11          15          19          23

In [55]:
#to sort [Put axis = 1 for columns and axis = 0 for rows]
df.sort_index(axis = 1,ascending = False)

D   C   B   A
2018-01-01   3   2   1   0
2018-01-02   7   6   5   4
2018-01-03  11  10   9   8
2018-01-04  15  14  13  12
2018-01-05  19  18  17  16
2018-01-06  23  22  21  20

In [57]:
#to sort by a particular column say C
df.sort_values(by='C',ascending = True)

A   B   C   D
2018-01-01   0   1   2   3
2018-01-02   4   5   6   7
2018-01-03   8   9  10  11
2018-01-04  12  13  14  15
2018-01-05  16  17  18  19
2018-01-06  20  21  22  23

In [58]:
df['B']

2018-01-01     1
2018-01-02     5
2018-01-03     9
2018-01-04    13
2018-01-05    17
2018-01-06    21
Freq: D, Name: B, dtype: int32

In [61]:
df[0:4]

A   B   C   D
2018-01-01   0   1   2   3
2018-01-02   4   5   6   7
2018-01-03   8   9  10  11
2018-01-04  12  13  14  15

In [66]:
#Selection using label location ->  .loc function
df.loc[:,'A':'C']    #all rows, selective columns

A   B   C
2018-01-01   0   1   2
2018-01-02   4   5   6
2018-01-03   8   9  10
2018-01-04  12  13  14
2018-01-05  16  17  18
2018-01-06  20  21  22

In [68]:
df.loc[:,['A','C']]

A   C
2018-01-01   0   2
2018-01-02   4   6
2018-01-03   8  10
2018-01-04  12  14
2018-01-05  16  18
2018-01-06  20  22

In [69]:
df.loc['2018-01-03',['A','C']]

A     8
C    10
Name: 2018-01-03 00:00:00, dtype: int32

In [70]:
df.loc['2018-01-03',['A','C']] [1] * 7     #it takes second row f result obtained in previous 

70

In [71]:
df.loc[dates_index[2],'A']                #use index values and subscript

8

In [72]:
numpy_data[2]

array([ 8,  9, 10, 11])

In [73]:
df.iloc[2]

A     8
B     9
C    10
D    11
Name: 2018-01-03 00:00:00, dtype: int32

In [76]:
df.iloc[1:3,1:4]           #2 rows from 1-3 and 3 columns from 1-4

B   C   D
2018-01-02  5   6   7
2018-01-03  9  10  11

In [79]:
# df.iloc[:,['C','D']]       # doesnt work because in iloc i can only use index values and nt column names
df.iloc[:,[2,3]]

C   D
2018-01-01   2   3
2018-01-02   6   7
2018-01-03  10  11
2018-01-04  14  15
2018-01-05  18  19
2018-01-06  22  23

In [80]:
df.C >= 13

2018-01-01    False
2018-01-02    False
2018-01-03    False
2018-01-04     True
2018-01-05     True
2018-01-06     True
Freq: D, Name: C, dtype: bool

In [81]:
df[df.C >= 13]

A   B   C   D
2018-01-04  12  13  14  15
2018-01-05  16  17  18  19
2018-01-06  20  21  22  23

In [84]:
df2 = df.copy()
df2['Veg'] = {'potato', 'tomato','lettuce','cabbage', 'cauliflower','peppars'}
df2

A   B   C   D          Veg
2018-01-01   0   1   2   3      lettuce
2018-01-02   4   5   6   7       tomato
2018-01-03   8   9  10  11       potato
2018-01-04  12  13  14  15  cauliflower
2018-01-05  16  17  18  19      peppars
2018-01-06  20  21  22  23      cabbage

In [86]:
df2[df2['Veg'].isin(['banana','tomato','apple'])]          #displays rows if its present in original column of dataframe

A  B  C  D     Veg
2018-01-02  4  5  6  7  tomato

In [89]:
#changing a particular value  --> .at[]
df2.at[dates_index[3],'Veg'] = 'caulflower'
df2

A   B   C   D         Veg
2018-01-01   0   1   2   3     lettuce
2018-01-02   4   5   6   7      tomato
2018-01-03   8   9  10  11      potato
2018-01-04  12  13  14  15  caulflower
2018-01-05  16  17  18  19     peppars
2018-01-06  20  21  22  23     cabbage

In [91]:
#or we can use index for both row and column value  ->   iat[]
df2.iat[1,4] = 'beans'
df2

A   B   C   D         Veg
2018-01-01   0   1   2   3     lettuce
2018-01-02   4   5   6   7       beans
2018-01-03   8   9  10  11      potato
2018-01-04  12  13  14  15  caulflower
2018-01-05  16  17  18  19     peppars
2018-01-06  20  21  22  23     cabbage

In [93]:
len(df2)   #no. of rows in the dataframe

6

In [117]:
df = df2.copy()

In [115]:
newindex = {'2018-01-01','2018-01-02','2018-01-03','2018-01-07','2018-01-08'}
df = df.reindex(newindex)

In [118]:
df

A   B   C   D         Veg
2018-01-01   0   1   2   3     lettuce
2018-01-02   4   5   6   7       beans
2018-01-03   8   9  10  11      potato
2018-01-04  12  13  14  15  caulflower
2018-01-05  16  17  18  19     peppars
2018-01-06  20  21  22  23     cabbage